version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      DB_CONNECTION_STRING: mongodb://mongo:27017/map
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_SECRET}
      FRONTEND_URL: https://holomap.frii.site
      BACKEND_URL: http://localhost:8000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}    
      S3_SECRET_KEY: ${S3_SECRET_KEY}  
      S3_DEFAULT_REGION: garage
      S3_ENDPOINT_URL: http://192.168.1.121:3900/
      S3_BUCKET_NAME: map-bucket
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: